<?php

class Person
{
    /**
     * Person's numeric identifier (usually generated by the database)
     *
     * @var int
     */
    protected $id;

    /**
     * Person's full name
     *
     * @var string
     */
    protected $name;

    /**
     * Person's billing address.
     *
     * @note  : I should have named this property billingAddress for clarity
     *        Regardless of the variable name, be sure to document all your properties.
     * @var string
     */
    protected $address;

    /**
     * Create a new person
     *
     * @param int    $id      personId from the database
     * @param string $name    Person's full name
     * @param string $address Billing address
     */
    public function __construct($id, $name, $address)
    {
        $this->id = $id;
        $this->name = $name;
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
}


class Student extends Person
{
    /**
     * An array of all courses that this student has taken
     *
     * @var array
     */
    protected $coursesTaken = array();

    /**
     * Add a course to the list of courses this student is taking
     *
     * @param string $courseName Name of the course this student is taking
     * @return Student
     */
    public function addTakenCourse($courseName)
    {
        $this->coursesTaken[] = $courseName;
        return $this;
    }
}

class Instructor extends Person
{
    /**
     * List of course names this instructor is teaching
     *
     * @var array
     */
    protected $coursesTaught = array();

    /**
     * Add a course to the array of courses this instructor is teaching
     *
     * @param string $courseName Name of the course this instructor is teaching
     * @return Instructor
     */
    public function addTaughtCourse($courseName)
    {
        $this->coursesTaught[] = $courseName;
        return $this;
    }
}

$IndustriousStudent = new Student(123, 'Albert Einstein', 'Munich, Germany');
$IndustriousStudent->addTakenCourse('Advanced Python')->addTakenCourse('Advanced PHP')->addTakenCourse('Particle Physics');
print_r($IndustriousStudent);

$ACAInstructor = new Instructor(456, 'Samir Patel', 'Austin TX');
$ACAInstructor->addTaughtCourse('Intermediate PHP');
$ACAInstructor->addTaughtCourse('Advanced PHP');
$ACAInstructor->addTaughtCourse('Golfing like a boss');
print_r($ACAInstructor);